// One-off generator for the second batch of 50 recipes. Not part of the deployed
// site (same convention as draft-recipe.ts) — run once, review output, delete or
// keep for reference. Writes directly to src/content/recipes/*.md.
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { stringify } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, "..", "src", "content", "recipes");
if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

const ing = (name_th, name_en, amount) => ({ name_th, name_en, amount });
const step = (th, en) => ({ th, en });

const recipes = [
  {
    slug: "gaeng-keow-wan-gai",
    title_th: "แกงเขียวหวานไก่", title_en: "Green Curry Chicken",
    calories: 430, protein: 49, carbs: 8, fat: 19,
    ingredients: [
      ing("อกไก่หั่นชิ้น", "Chicken breast, sliced", "150g"),
      ing("กะทิไขมันต่ำ", "Light coconut milk", "150ml"),
      ing("พริกแกงเขียวหวาน", "Green curry paste", "2 tbsp"),
      ing("มะเขือเปราะ", "Thai eggplant", "6 pieces"),
      ing("ใบโหระพา", "Thai basil leaves", "1/2 cup"),
      ing("พริกชี้ฟ้าแดง", "Red spur chili", "1, sliced"),
    ],
    steps: [
      step("ตั้งกะทิให้แตกมัน ใส่พริกแกงผัดจนหอม", "Simmer coconut milk until the oil separates, add curry paste and fry until fragrant"),
      step("ใส่อกไก่ ผัดจนเปลี่ยนสี", "Add chicken breast, stir until it changes color"),
      step("เติมกะทิที่เหลือและมะเขือเปราะ ต้มจนไก่สุกและมะเขือนุ่ม", "Add remaining coconut milk and eggplant, simmer until chicken is cooked and eggplant is tender"),
      step("ใส่ใบโหระพาและพริกชี้ฟ้า ปิดไฟ เสิร์ฟ", "Add basil leaves and chili, turn off heat, serve"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "gaeng-phed-moo",
    title_th: "แกงเผ็ดหมู", title_en: "Red Curry Pork",
    calories: 380, protein: 41, carbs: 8, fat: 19,
    ingredients: [
      ing("หมูสันในหั่นชิ้น", "Pork tenderloin, sliced", "150g"),
      ing("กะทิไขมันต่ำ", "Light coconut milk", "150ml"),
      ing("พริกแกงแดง", "Red curry paste", "2 tbsp"),
      ing("พริกชี้ฟ้าแดง", "Red spur chili", "2, sliced"),
      ing("ใบมะกรูด", "Kaffir lime leaves", "3 leaves"),
      ing("ใบโหระพา", "Thai basil leaves", "1/2 cup"),
    ],
    steps: [
      step("ตั้งกะทิให้แตกมัน ใส่พริกแกงผัดจนหอม", "Simmer coconut milk until the oil separates, add curry paste and fry until fragrant"),
      step("ใส่หมูสันใน ผัดจนสุกทั่ว", "Add pork tenderloin, stir until fully cooked"),
      step("เติมกะทิที่เหลือและใบมะกรูด ต้มพอเดือด", "Add remaining coconut milk and kaffir lime leaves, bring to a light boil"),
      step("ใส่พริกชี้ฟ้าและใบโหระพา ปิดไฟ เสิร์ฟ", "Add chili and basil, turn off heat, serve"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "pad-see-ew-gai",
    title_th: "ผัดซีอิ๊วไก่", title_en: "Pad See Ew Chicken",
    calories: 545, protein: 48, carbs: 56, fat: 10,
    ingredients: [
      ing("อกไก่หั่นชิ้น", "Chicken breast, sliced", "120g"),
      ing("เส้นใหญ่", "Fresh flat rice noodles", "150g"),
      ing("ไข่ไก่", "Egg", "1 large"),
      ing("คะน้า", "Chinese kale", "1 cup, chopped"),
      ing("ซีอิ๊วดำ", "Dark soy sauce", "1 tbsp"),
      ing("ซีอิ๊วขาว", "Light soy sauce", "1 tbsp"),
    ],
    steps: [
      step("ผัดกระเทียมกับน้ำมันเล็กน้อยจนหอม ใส่อกไก่ผัดจนสุก", "Stir-fry garlic in a little oil until fragrant, add chicken and cook through"),
      step("ใส่เส้นใหญ่ ซีอิ๊วดำ และซีอิ๊วขาว ผัดเร็วๆ ให้เข้ากัน", "Add flat noodles, dark and light soy sauce, toss quickly to combine"),
      step("ดันวัตถุดิบไปด้านหนึ่ง ตอกไข่ลงผัดให้สุก แล้วคลุกรวมกัน", "Push ingredients to one side, crack in the egg and scramble, then mix together"),
      step("ใส่คะน้า ผัดจนสุกกรอบ เสิร์ฟร้อน", "Add Chinese kale, stir-fry until just tender, serve hot"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "dinner", "one-dish"], regionTags: ["central-thai"],
  },
  {
    slug: "kana-moo-krob",
    title_th: "คะน้าหมูกรอบ", title_en: "Stir-Fried Kai-lan with Lean Pork",
    calories: 250, protein: 33, carbs: 9, fat: 5,
    ingredients: [
      ing("คะน้า", "Chinese kale", "200g"),
      ing("หมูสันในหั่นบาง", "Lean pork loin, thinly sliced", "120g"),
      ing("กระเทียม", "Garlic", "3 cloves"),
      ing("น้ำมันหอย", "Oyster sauce", "1 tbsp"),
      ing("ซีอิ๊วขาว", "Light soy sauce", "1 tsp"),
    ],
    steps: [
      step("ลวกคะน้าในน้ำเดือดสั้นๆ พักสะเด็ดน้ำ", "Briefly blanch the kai-lan in boiling water, drain"),
      step("ผัดกระเทียมกับน้ำมันเล็กน้อยจนหอม ใส่หมูผัดจนสุก", "Stir-fry garlic in a little oil until fragrant, add pork and cook through"),
      step("ปรุงรสด้วยน้ำมันหอยและซีอิ๊วขาว", "Season with oyster sauce and light soy sauce"),
      step("ใส่คะน้าที่ลวกไว้ ผัดเร็วๆ ให้เข้ากัน เสิร์ฟ", "Add the blanched kai-lan, toss quickly to combine, serve"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "tom-kha-gai",
    title_th: "ต้มข่าไก่", title_en: "Tom Kha Gai",
    calories: 460, protein: 49, carbs: 8, fat: 24,
    ingredients: [
      ing("อกไก่หั่นชิ้น", "Chicken breast, sliced", "150g"),
      ing("กะทิไขมันต่ำ", "Light coconut milk", "200ml"),
      ing("ข่า", "Galangal", "5 slices"),
      ing("ตะไคร้", "Lemongrass", "2 stalks"),
      ing("เห็ดฟาง", "Straw mushrooms", "1 cup"),
      ing("น้ำมะนาว", "Lime juice", "2 tbsp"),
    ],
    steps: [
      step("ต้มกะทิกับข่าและตะไคร้ให้หอม", "Simmer coconut milk with galangal and lemongrass until fragrant"),
      step("ใส่อกไก่และเห็ดฟาง ต้มจนไก่สุก", "Add chicken and straw mushrooms, simmer until the chicken is cooked"),
      step("ปรุงรสด้วยน้ำปลาและน้ำมะนาว", "Season with fish sauce and lime juice"),
      step("ตักเสิร์ฟร้อนๆ", "Serve hot"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "pad-pak-boong-fai-daeng",
    title_th: "ผัดผักบุ้งไฟแดง", title_en: "Stir-Fried Morning Glory",
    calories: 115, protein: 6, carbs: 16, fat: 3,
    ingredients: [
      ing("ผักบุ้ง", "Morning glory", "200g"),
      ing("กระเทียม", "Garlic", "4 cloves"),
      ing("พริกขี้หนู", "Thai chilies", "3 chilies"),
      ing("เต้าเจี้ยว", "Fermented soybean paste", "1 tsp"),
      ing("น้ำมันหอย", "Oyster sauce", "1 tbsp"),
    ],
    steps: [
      step("โขลกกระเทียมและพริกขี้หนูพอหยาบ", "Roughly pound garlic and chilies"),
      step("ผัดกระเทียมพริกในกระทะร้อนจัดจนหอม", "Stir-fry the garlic-chili paste in a very hot pan until fragrant"),
      step("ใส่ผักบุ้ง ผัดเร็วๆ ด้วยไฟแรง", "Add morning glory, stir-fry quickly over high heat"),
      step("ปรุงรสด้วยเต้าเจี้ยวและน้ำมันหอย ผัดให้เข้ากัน เสิร์ฟทันที", "Season with soybean paste and oyster sauce, toss to combine, serve immediately"),
    ],
    dietTags: ["vegetarian", "low-carb"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "pla-tod-nam-pla",
    title_th: "ปลาทอดน้ำปลา", title_en: "Fish Sauce Baked Fish",
    calories: 220, protein: 42, carbs: 2, fat: 3,
    ingredients: [
      ing("ปลานิลหรือปลากะพง", "Tilapia or sea bass fillet", "200g"),
      ing("น้ำปลา", "Fish sauce", "1 tbsp"),
      ing("กระเทียม", "Garlic", "3 cloves, minced"),
      ing("พริกไทย", "White pepper", "1/4 tsp"),
      ing("ผักชี", "Cilantro", "for garnish"),
    ],
    steps: [
      step("หมักปลาด้วยน้ำปลา กระเทียม และพริกไทย 15 นาที", "Marinate the fish with fish sauce, garlic, and white pepper for 15 minutes"),
      step("อบที่ 200°C จนสุกทั่วและผิวเริ่มเหลือง", "Bake at 200°C until fully cooked and lightly golden"),
      step("ทำน้ำจิ้มด้วยน้ำปลา มะนาว และพริกขี้หนู", "Make a dipping sauce with fish sauce, lime, and Thai chilies"),
      step("โรยผักชี เสิร์ฟพร้อมน้ำจิ้ม", "Garnish with cilantro, serve with the dipping sauce"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "gai-pad-med-mamuang",
    title_th: "ไก่ผัดเม็ดมะม่วง", title_en: "Cashew Chicken",
    calories: 415, protein: 52, carbs: 18, fat: 16,
    ingredients: [
      ing("อกไก่หั่นชิ้น", "Chicken breast, sliced", "150g"),
      ing("เม็ดมะม่วงหิมพานต์คั่ว", "Roasted cashews", "20g"),
      ing("หอมใหญ่", "Onion", "1/2, sliced"),
      ing("พริกหยวก", "Bell pepper", "1/2, sliced"),
      ing("ซีอิ๊วขาว", "Light soy sauce", "1 tbsp"),
      ing("ซอสหอยนางรม", "Oyster sauce", "1 tbsp"),
    ],
    steps: [
      step("ผัดกระเทียมกับน้ำมันเล็กน้อยจนหอม ใส่อกไก่ผัดจนสุก", "Stir-fry garlic in a little oil until fragrant, add chicken and cook through"),
      step("ใส่หอมใหญ่และพริกหยวก ผัดจนเริ่มนุ่ม", "Add onion and bell pepper, stir-fry until starting to soften"),
      step("ปรุงรสด้วยซีอิ๊วขาวและซอสหอยนางรม", "Season with light soy sauce and oyster sauce"),
      step("ใส่เม็ดมะม่วงหิมพานต์ ผัดให้เข้ากัน เสิร์ฟ", "Add the cashews, toss to combine, serve"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "tom-jued-mara-yad-sai",
    title_th: "ต้มจืดมะระยัดไส้", title_en: "Stuffed Bitter Melon Soup",
    calories: 175, protein: 27, carbs: 4, fat: 3,
    ingredients: [
      ing("มะระ", "Bitter melon", "1 piece, sliced into rings"),
      ing("หมูสันในสับ", "Ground pork tenderloin", "100g"),
      ing("กระเทียม", "Garlic", "2 cloves, minced"),
      ing("รากผักชี", "Cilantro root", "1, minced"),
      ing("ซีอิ๊วขาว", "Light soy sauce", "1 tbsp"),
      ing("ต้นหอม", "Spring onion", "1 stalk, chopped"),
    ],
    steps: [
      step("ผสมหมูสับกับกระเทียม รากผักชี และซีอิ๊วขาว", "Mix the ground pork with garlic, cilantro root, and light soy sauce"),
      step("ยัดไส้หมูลงในวงมะระ", "Stuff the pork mixture into the bitter melon rings"),
      step("ต้มน้ำซุปให้เดือด ใส่มะระยัดไส้ลงต้มจนสุก", "Bring stock to a boil, add the stuffed bitter melon, simmer until cooked"),
      step("ปรุงรสด้วยซีอิ๊วขาว โรยต้นหอม เสิร์ฟร้อน", "Season with light soy sauce, top with spring onion, serve hot"),
    ],
    dietTags: ["high-protein", "low-cal"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "khao-pad-goong",
    title_th: "ข้าวผัดกุ้ง", title_en: "Shrimp Fried Rice",
    calories: 435, protein: 36, carbs: 56, fat: 8,
    ingredients: [
      ing("กุ้ง", "Shrimp", "120g"),
      ing("ข้าวสวย", "Steamed rice", "180g"),
      ing("ไข่ไก่", "Egg", "1 large"),
      ing("หอมใหญ่", "Onion", "1/4, diced"),
      ing("ซีอิ๊วขาว", "Light soy sauce", "1 tbsp"),
      ing("ต้นหอม", "Spring onion", "1 stalk, chopped"),
    ],
    steps: [
      step("ผัดกระเทียมกับน้ำมันเล็กน้อยจนหอม ใส่กุ้งผัดจนสุก พักไว้", "Stir-fry garlic in a little oil until fragrant, add shrimp until cooked, set aside"),
      step("ตอกไข่ลงผัดในกระทะเดิมให้สุก", "Crack the egg into the same pan and scramble until cooked"),
      step("ใส่ข้าวสวยและหอมใหญ่ ผัดให้เข้ากันด้วยไฟแรง", "Add the rice and onion, stir-fry over high heat until combined"),
      step("ปรุงรสด้วยซีอิ๊วขาว ใส่กุ้งกลับลงไป โรยต้นหอม เสิร์ฟ", "Season with light soy sauce, return the shrimp, top with spring onion, serve"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "dinner", "one-dish"], regionTags: ["central-thai"],
  },
  {
    slug: "gaeng-som",
    title_th: "แกงส้ม", title_en: "Sour Curry with Fish",
    calories: 200, protein: 34, carbs: 10, fat: 2,
    ingredients: [
      ing("ปลากะพงหั่นชิ้น", "Sea bass, sliced", "150g"),
      ing("พริกแกงส้ม", "Sour curry paste", "1 tbsp"),
      ing("มะขามเปียก", "Tamarind paste", "1 tbsp"),
      ing("ผักรวม (ผักกาดขาว, ถั่วฝักยาว)", "Mixed vegetables (napa cabbage, long beans)", "1 cup"),
      ing("น้ำปลา", "Fish sauce", "1 tbsp"),
    ],
    steps: [
      step("ต้มน้ำให้เดือด ละลายพริกแกงส้มลงไป", "Bring water to a boil, dissolve the sour curry paste"),
      step("ใส่ผักรวม ต้มจนเริ่มนุ่ม", "Add mixed vegetables, simmer until starting to soften"),
      step("ใส่ปลา ต้มจนสุก", "Add the fish, simmer until cooked"),
      step("ปรุงรสด้วยมะขามเปียกและน้ำปลา เสิร์ฟร้อน", "Season with tamarind paste and fish sauce, serve hot"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "moo-ping",
    title_th: "หมูปิ้ง", title_en: "Grilled Pork Skewers",
    calories: 260, protein: 34, carbs: 6, fat: 9,
    ingredients: [
      ing("หมูสะโพกหั่นบาง", "Lean pork shoulder, thinly sliced", "150g"),
      ing("กระเทียม", "Garlic", "3 cloves"),
      ing("รากผักชี", "Cilantro root", "1"),
      ing("ซีอิ๊วขาว", "Light soy sauce", "1 tbsp"),
      ing("น้ำผึ้ง", "Honey", "1 tsp"),
    ],
    steps: [
      step("โขลกกระเทียมและรากผักชีให้ละเอียด", "Pound garlic and cilantro root until fine"),
      step("หมักหมูกับเครื่องที่โขลก ซีอิ๊วขาว และน้ำผึ้ง อย่างน้อย 1 ชั่วโมง", "Marinate the pork with the pounded paste, soy sauce, and honey for at least 1 hour"),
      step("เสียบไม้ ย่างบนเตาถ่านหรือกระทะย่างจนสุกทั่ว", "Skewer and grill over charcoal or a grill pan until fully cooked"),
      step("เสิร์ฟพร้อมข้าวเหนียวหรือข้าวสวย", "Serve with sticky rice or steamed rice"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "snack"], regionTags: ["central-thai"],
  },
  {
    slug: "som-tam-thai",
    title_th: "ส้มตำไทย", title_en: "Som Tam Thai",
    calories: 120, protein: 4, carbs: 20, fat: 3,
    ingredients: [
      ing("มะละกอดิบสับ", "Shredded green papaya", "200g"),
      ing("มะเขือเทศ", "Tomato", "2, sliced"),
      ing("ถั่วฝักยาว", "Long beans", "3, cut"),
      ing("ถั่วลิสงคั่ว", "Roasted peanuts", "1 tbsp"),
      ing("กุ้งแห้ง", "Dried shrimp", "1 tbsp"),
      ing("น้ำมะนาว", "Lime juice", "2 tbsp"),
    ],
    steps: [
      step("โขลกกระเทียมและพริกขี้หนูพอแตก", "Pound garlic and chilies until lightly crushed"),
      step("ใส่ถั่วฝักยาวและมะเขือเทศ โขลกเบาๆ พอช้ำ", "Add long beans and tomato, lightly pound to bruise"),
      step("ใส่มะละกอ ปรุงรสด้วยน้ำปลา น้ำตาลปี๊บ และน้ำมะนาว โขลกเบาๆ ให้เข้ากัน", "Add papaya, season with fish sauce, palm sugar, and lime juice, lightly pound to combine"),
      step("ใส่กุ้งแห้งและถั่วลิสง คลุกให้เข้ากัน เสิร์ฟ", "Add dried shrimp and peanuts, toss to combine, serve"),
    ],
    dietTags: ["low-cal"], mealTypeTags: ["lunch", "snack"], regionTags: ["isaan"],
  },
  {
    slug: "som-tam-poo-pla-ra",
    title_th: "ส้มตำปูปลาร้า", title_en: "Som Tam with Salted Crab",
    calories: 140, protein: 8, carbs: 20, fat: 4,
    ingredients: [
      ing("มะละกอดิบสับ", "Shredded green papaya", "200g"),
      ing("ปูดอง", "Salted crab", "1 piece"),
      ing("น้ำปลาร้า", "Fermented fish sauce", "1 tbsp"),
      ing("มะเขือเทศ", "Tomato", "2, sliced"),
      ing("ถั่วฝักยาว", "Long beans", "3, cut"),
      ing("น้ำมะนาว", "Lime juice", "1 tbsp"),
    ],
    steps: [
      step("โขลกกระเทียมและพริกขี้หนูพอแตก", "Pound garlic and chilies until lightly crushed"),
      step("ใส่ถั่วฝักยาวและมะเขือเทศ โขลกเบาๆ พอช้ำ", "Add long beans and tomato, lightly pound to bruise"),
      step("ใส่มะละกอ ปูดอง และน้ำปลาร้า โขลกเบาๆ ให้เข้ากัน", "Add papaya, salted crab, and fermented fish sauce, lightly pound to combine"),
      step("ปรุงรสด้วยน้ำมะนาว คลุกให้เข้ากัน เสิร์ฟ", "Season with lime juice, toss to combine, serve"),
    ],
    dietTags: ["low-cal"], mealTypeTags: ["lunch", "snack"], regionTags: ["isaan"],
  },
  {
    slug: "gai-yang",
    title_th: "ไก่ย่าง", title_en: "Isaan Grilled Chicken",
    calories: 320, protein: 50, carbs: 4, fat: 9,
    ingredients: [
      ing("น่องไก่ไม่ติดหนัง", "Skinless chicken thigh", "200g"),
      ing("กระเทียม", "Garlic", "4 cloves"),
      ing("รากผักชี", "Cilantro root", "2"),
      ing("พริกไทย", "White peppercorns", "1 tsp"),
      ing("ซีอิ๊วขาว", "Light soy sauce", "1 tbsp"),
    ],
    steps: [
      step("โขลกกระเทียม รากผักชี และพริกไทยให้ละเอียด", "Pound garlic, cilantro root, and peppercorns until fine"),
      step("หมักไก่กับเครื่องที่โขลกและซีอิ๊วขาว อย่างน้อย 2 ชั่วโมง", "Marinate the chicken with the pounded paste and soy sauce for at least 2 hours"),
      step("ย่างบนเตาถ่านไฟอ่อนจนสุกทั่วและผิวเกรียม", "Grill over low charcoal heat until fully cooked with a charred skin"),
      step("สับเป็นชิ้น เสิร์ฟพร้อมน้ำจิ้มแจ่ว", "Chop into pieces, serve with jaew dipping sauce"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "dinner"], regionTags: ["isaan"],
  },
  {
    slug: "larb-gai",
    title_th: "ลาบไก่", title_en: "Larb Gai (Minced Chicken Salad)",
    calories: 280, protein: 48, carbs: 6, fat: 6,
    ingredients: [
      ing("อกไก่สับ", "Ground chicken breast", "150g"),
      ing("ข้าวคั่ว", "Toasted rice powder", "1 tbsp"),
      ing("น้ำปลา", "Fish sauce", "1 tbsp"),
      ing("น้ำมะนาว", "Lime juice", "2 tbsp"),
      ing("หอมแดง", "Shallot", "3 pieces, sliced"),
      ing("ใบสะระแหน่", "Mint leaves", "1/2 cup"),
    ],
    steps: [
      step("ต้มอกไก่สับในน้ำเดือดจนสุก คนให้ไม่จับตัวเป็นก้อน", "Simmer the ground chicken in boiling water until cooked, stirring to keep it from clumping"),
      step("สะเด็ดน้ำ พักให้เย็นเล็กน้อย", "Drain and let cool slightly"),
      step("ปรุงรสด้วยน้ำปลา น้ำมะนาว และพริกป่น", "Season with fish sauce, lime juice, and chili flakes"),
      step("ใส่ข้าวคั่ว หอมแดง และใบสะระแหน่ คลุกให้เข้ากัน เสิร์ฟ", "Add toasted rice powder, shallot, and mint, toss to combine, serve"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["lunch", "dinner"], regionTags: ["isaan"],
  },
  {
    slug: "nam-tok-moo",
    title_th: "น้ำตกหมู", title_en: "Nam Tok Moo (Waterfall Pork Salad)",
    calories: 250, protein: 39, carbs: 4, fat: 8,
    ingredients: [
      ing("หมูสันในย่างหั่นบาง", "Grilled lean pork, thinly sliced", "150g"),
      ing("ข้าวคั่ว", "Toasted rice powder", "1 tbsp"),
      ing("น้ำปลา", "Fish sauce", "1 tbsp"),
      ing("น้ำมะนาว", "Lime juice", "2 tbsp"),
      ing("ต้นหอม", "Spring onion", "2 stalks, chopped"),
      ing("ใบสะระแหน่", "Mint leaves", "1/2 cup"),
    ],
    steps: [
      step("ย่างหมูสันในจนสุก พักให้เย็นเล็กน้อย แล้วหั่นบาง", "Grill the pork tenderloin until cooked, let cool slightly, then slice thin"),
      step("ปรุงรสด้วยน้ำปลา น้ำมะนาว และพริกป่น", "Season with fish sauce, lime juice, and chili flakes"),
      step("ใส่ข้าวคั่วและต้นหอม คลุกให้เข้ากัน", "Add toasted rice powder and spring onion, toss to combine"),
      step("โรยใบสะระแหน่ก่อนเสิร์ฟ", "Top with mint leaves before serving"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["lunch", "dinner"], regionTags: ["isaan"],
  },
  {
    slug: "tom-saep-kraduk-moo",
    title_th: "ต้มแซ่บกระดูกหมู", title_en: "Spicy Pork Rib Soup",
    calories: 360, protein: 41, carbs: 4, fat: 18,
    ingredients: [
      ing("ซี่โครงหมูตัดแต่งไขมัน", "Trimmed pork ribs", "200g"),
      ing("ตะไคร้", "Lemongrass", "2 stalks"),
      ing("ใบมะกรูด", "Kaffir lime leaves", "3 leaves"),
      ing("น้ำมะนาว", "Lime juice", "2 tbsp"),
      ing("พริกป่น", "Chili flakes", "1 tsp"),
      ing("ผักชีฝรั่ง", "Sawtooth coriander", "for garnish"),
    ],
    steps: [
      step("ต้มซี่โครงหมูกับตะไคร้จนเนื้อนุ่ม", "Boil the pork ribs with lemongrass until tender"),
      step("ใส่ใบมะกรูด ต้มต่อให้หอม", "Add kaffir lime leaves, continue simmering until fragrant"),
      step("ปรุงรสด้วยน้ำปลา น้ำมะนาว และพริกป่น", "Season with fish sauce, lime juice, and chili flakes"),
      step("โรยผักชีฝรั่ง เสิร์ฟร้อน", "Top with sawtooth coriander, serve hot"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "dinner"], regionTags: ["isaan"],
  },
  {
    slug: "tam-thua",
    title_th: "ตำถั่ว", title_en: "Bean Som Tam",
    calories: 110, protein: 4, carbs: 14, fat: 4,
    ingredients: [
      ing("ถั่วฝักยาว", "Long beans", "150g, cut"),
      ing("มะเขือเทศ", "Tomato", "2, sliced"),
      ing("ถั่วลิสงคั่ว", "Roasted peanuts", "1 tbsp"),
      ing("กระเทียม", "Garlic", "3 cloves"),
      ing("น้ำมะนาว", "Lime juice", "2 tbsp"),
    ],
    steps: [
      step("โขลกกระเทียมและพริกขี้หนูพอแตก", "Pound garlic and chilies until lightly crushed"),
      step("ใส่ถั่วฝักยาว โขลกเบาๆ พอช้ำ", "Add long beans, lightly pound to bruise"),
      step("ใส่มะเขือเทศ ปรุงรสด้วยน้ำปลา น้ำตาลปี๊บ และน้ำมะนาว", "Add tomato, season with fish sauce, palm sugar, and lime juice"),
      step("ใส่ถั่วลิสง คลุกให้เข้ากัน เสิร์ฟ", "Add peanuts, toss to combine, serve"),
    ],
    dietTags: ["vegetarian", "low-cal"], mealTypeTags: ["lunch", "snack"], regionTags: ["isaan"],
  },
  {
    slug: "larb-hed",
    title_th: "ลาบเห็ด", title_en: "Mushroom Larb",
    calories: 100, protein: 7, carbs: 16, fat: 2,
    ingredients: [
      ing("เห็ดรวม (เห็ดฟาง, เห็ดนางฟ้า)", "Mixed mushrooms (straw, oyster)", "200g, torn"),
      ing("ข้าวคั่ว", "Toasted rice powder", "1 tbsp"),
      ing("น้ำมะนาว", "Lime juice", "2 tbsp"),
      ing("หอมแดง", "Shallot", "2 pieces, sliced"),
      ing("ใบสะระแหน่", "Mint leaves", "1/2 cup"),
    ],
    steps: [
      step("ต้มหรือนึ่งเห็ดจนสุก สะเด็ดน้ำ", "Boil or steam the mushrooms until cooked, drain"),
      step("ปรุงรสด้วยซีอิ๊วขาว น้ำมะนาว และพริกป่น", "Season with light soy sauce, lime juice, and chili flakes"),
      step("ใส่ข้าวคั่วและหอมแดง คลุกให้เข้ากัน", "Add toasted rice powder and shallot, toss to combine"),
      step("โรยใบสะระแหน่ก่อนเสิร์ฟ", "Top with mint leaves before serving"),
    ],
    dietTags: ["vegetarian", "low-cal"], mealTypeTags: ["lunch", "dinner"], regionTags: ["isaan"],
  },
  {
    slug: "gaeng-hang-lay",
    title_th: "แกงฮังเล", title_en: "Gaeng Hang Lay (Northern Pork Curry)",
    calories: 290, protein: 34, carbs: 10, fat: 11,
    ingredients: [
      ing("หมูสะโพกหั่นชิ้น", "Lean pork shoulder, cubed", "150g"),
      ing("พริกแกงฮังเล", "Hang lay curry paste", "1 tbsp"),
      ing("ขิงซอย", "Ginger, julienned", "2 tbsp"),
      ing("มะขามเปียก", "Tamarind paste", "1 tbsp"),
      ing("ถั่วลิสง", "Peanuts", "1 tbsp"),
    ],
    steps: [
      step("ผัดพริกแกงฮังเลกับน้ำมันเล็กน้อยจนหอม", "Stir-fry the hang lay curry paste in a little oil until fragrant"),
      step("ใส่หมู ผัดจนเปลี่ยนสี", "Add the pork, stir until it changes color"),
      step("เติมน้ำและขิงซอย ต้มไฟอ่อนจนหมูนุ่ม", "Add water and ginger, simmer on low heat until the pork is tender"),
      step("ปรุงรสด้วยมะขามเปียก ใส่ถั่วลิสง เสิร์ฟ", "Season with tamarind paste, add peanuts, serve"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "dinner"], regionTags: ["northern-thai"],
  },
  {
    slug: "nam-prik-num",
    title_th: "น้ำพริกหนุ่ม", title_en: "Nam Prik Num (Roasted Green Chili Dip)",
    calories: 60, protein: 2, carbs: 10, fat: 1,
    ingredients: [
      ing("พริกหนุ่ม", "Green chilies", "6 pieces"),
      ing("กระเทียม", "Garlic", "5 cloves"),
      ing("หอมแดง", "Shallot", "3 pieces"),
      ing("น้ำปลา", "Fish sauce", "1 tbsp"),
      ing("ผักสด (แตงกวา, กะหล่ำปลี)", "Fresh vegetables (cucumber, cabbage)", "for serving"),
    ],
    steps: [
      step("ย่างพริกหนุ่ม กระเทียม และหอมแดงจนผิวไหม้เกรียม", "Grill the green chilies, garlic, and shallot until the skin is charred"),
      step("ปอกเปลือกที่ไหม้ออก", "Peel off the charred skin"),
      step("โขลกทุกอย่างรวมกันพอหยาบ", "Pound everything together until roughly combined"),
      step("ปรุงรสด้วยน้ำปลา เสิร์ฟพร้อมผักสด", "Season with fish sauce, serve with fresh vegetables"),
    ],
    dietTags: ["vegetarian", "low-cal"], mealTypeTags: ["lunch", "snack"], regionTags: ["northern-thai"],
  },
  {
    slug: "sai-ua",
    title_th: "ไส้อั่ว", title_en: "Northern Herb Sausage (Baked)",
    calories: 245, protein: 29, carbs: 5, fat: 10,
    ingredients: [
      ing("หมูสันในสับ", "Ground pork tenderloin", "150g"),
      ing("พริกแกงไส้อั่ว", "Sai ua curry paste", "1 tbsp"),
      ing("ตะไคร้ซอย", "Sliced lemongrass", "2 tbsp"),
      ing("ใบมะกรูดซอย", "Sliced kaffir lime leaves", "1 tbsp"),
      ing("ผักชี", "Cilantro", "2 tbsp, chopped"),
    ],
    steps: [
      step("ผสมหมูสับกับพริกแกง ตะไคร้ ใบมะกรูด และผักชีให้เข้ากัน", "Mix the ground pork with curry paste, lemongrass, kaffir lime leaves, and cilantro until combined"),
      step("ปั้นเป็นแท่งยาวคล้ายไส้กรอก", "Shape into long sausage-like logs"),
      step("อบที่ 190°C จนสุกทั่วและผิวเริ่มเหลือง", "Bake at 190°C until fully cooked and lightly golden"),
      step("หั่นเป็นชิ้น เสิร์ฟพร้อมผักสด", "Slice and serve with fresh vegetables"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "dinner"], regionTags: ["northern-thai"],
  },
  {
    slug: "gaeng-ho",
    title_th: "แกงโฮะ", title_en: "Gaeng Ho (Mixed Curry Noodles)",
    calories: 290, protein: 28, carbs: 33, fat: 5,
    ingredients: [
      ing("หมูสันในสับ", "Ground pork tenderloin", "100g"),
      ing("วุ้นเส้น", "Glass noodles (dry)", "30g"),
      ing("หน่อไม้ต้ม", "Boiled bamboo shoots", "1/2 cup"),
      ing("พริกแกงฮังเล", "Hang lay curry paste", "1 tbsp"),
      ing("ใบมะกรูดซอย", "Sliced kaffir lime leaves", "1 tbsp"),
    ],
    steps: [
      step("แช่วุ้นเส้นในน้ำอุ่นจนนุ่ม สะเด็ดน้ำ", "Soak glass noodles in warm water until soft, drain"),
      step("ผัดพริกแกงกับน้ำมันเล็กน้อยจนหอม ใส่หมูผัดจนสุก", "Stir-fry the curry paste in a little oil until fragrant, add pork and cook through"),
      step("ใส่หน่อไม้และน้ำเล็กน้อย ต้มพอเดือด", "Add bamboo shoots and a little water, bring to a light boil"),
      step("ใส่วุ้นเส้นและใบมะกรูด ผัดให้เข้ากัน เสิร์ฟ", "Add glass noodles and kaffir lime leaves, toss to combine, serve"),
    ],
    mealTypeTags: ["lunch", "dinner", "one-dish"], regionTags: ["northern-thai"],
  },
  {
    slug: "khao-soi-gai",
    title_th: "ข้าวซอยไก่", title_en: "Khao Soi Gai",
    calories: 580, protein: 46, carbs: 38, fat: 26,
    ingredients: [
      ing("น่องไก่ไม่ติดหนัง", "Skinless chicken thigh", "150g"),
      ing("กะทิไขมันต่ำ", "Light coconut milk", "150ml"),
      ing("พริกแกงข้าวซอย", "Khao soi curry paste", "1.5 tbsp"),
      ing("บะหมี่ไข่ต้ม", "Boiled egg noodles", "50g dry weight"),
      ing("หอมแดงดอง", "Pickled shallot", "for garnish"),
      ing("ผักกาดดอง", "Pickled mustard greens", "for garnish"),
    ],
    steps: [
      step("ผัดพริกแกงข้าวซอยกับน้ำมันเล็กน้อยจนหอม", "Stir-fry the khao soi curry paste in a little oil until fragrant"),
      step("ใส่กะทิและไก่ ต้มจนไก่สุกและน้ำแกงเข้มข้น", "Add coconut milk and chicken, simmer until the chicken is cooked and the broth thickens"),
      step("ลวกบะหมี่ไข่ให้สุก จัดใส่ชาม", "Blanch the egg noodles until cooked, place in a bowl"),
      step("ราดน้ำแกงไก่ลงบนเส้น โรยหอมแดงดองและผักกาดดอง เสิร์ฟ", "Ladle the chicken curry over the noodles, top with pickled shallot and mustard greens, serve"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "dinner", "one-dish"], regionTags: ["northern-thai"],
  },
  {
    slug: "tam-khanun",
    title_th: "ตำขนุน", title_en: "Young Jackfruit Salad",
    calories: 100, protein: 3, carbs: 20, fat: 1,
    ingredients: [
      ing("ขนุนอ่อนต้ม", "Boiled young jackfruit", "200g, shredded"),
      ing("กระเทียม", "Garlic", "3 cloves"),
      ing("พริกขี้หนู", "Thai chilies", "3 chilies"),
      ing("น้ำมะนาว", "Lime juice", "2 tbsp"),
      ing("ใบสะระแหน่", "Mint leaves", "for garnish"),
    ],
    steps: [
      step("ต้มขนุนอ่อนจนนุ่ม สะเด็ดน้ำ ฉีกเป็นเส้น", "Boil the young jackfruit until tender, drain, shred into pieces"),
      step("โขลกกระเทียมและพริกขี้หนูพอแตก", "Pound garlic and chilies until lightly crushed"),
      step("ใส่ขนุน ปรุงรสด้วยน้ำปลาและน้ำมะนาว โขลกเบาๆ ให้เข้ากัน", "Add jackfruit, season with fish sauce and lime juice, lightly pound to combine"),
      step("โรยใบสะระแหน่ เสิร์ฟ", "Top with mint leaves, serve"),
    ],
    dietTags: ["vegetarian", "low-cal"], mealTypeTags: ["lunch", "snack"], regionTags: ["northern-thai"],
  },
  {
    slug: "gaeng-tai-pla",
    title_th: "แกงไตปลา", title_en: "Gaeng Tai Pla (Southern Fish Curry)",
    calories: 210, protein: 35, carbs: 8, fat: 4,
    ingredients: [
      ing("ปลากะพงหั่นชิ้น", "Sea bass, sliced", "150g"),
      ing("พริกแกงไตปลา", "Tai pla curry paste", "1.5 tbsp"),
      ing("มะเขือเปราะ", "Thai eggplant", "5 pieces"),
      ing("ถั่วฝักยาว", "Long beans", "1/2 cup, cut"),
      ing("ใบมะกรูด", "Kaffir lime leaves", "3 leaves"),
    ],
    steps: [
      step("ต้มน้ำให้เดือด ละลายพริกแกงไตปลาลงไป", "Bring water to a boil, dissolve the tai pla curry paste"),
      step("ใส่มะเขือเปราะและถั่วฝักยาว ต้มจนเริ่มนุ่ม", "Add eggplant and long beans, simmer until starting to soften"),
      step("ใส่ปลาและใบมะกรูด ต้มจนปลาสุก", "Add fish and kaffir lime leaves, simmer until the fish is cooked"),
      step("ตักเสิร์ฟร้อนๆ", "Serve hot"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["lunch", "dinner"], regionTags: ["southern-thai"],
  },
  {
    slug: "khua-kling-moo",
    title_th: "คั่วกลิ้งหมู", title_en: "Khua Kling Moo (Dry-Fried Spicy Pork)",
    calories: 255, protein: 29, carbs: 6, fat: 11,
    ingredients: [
      ing("หมูสันในสับ", "Ground pork tenderloin", "150g"),
      ing("พริกแกงคั่วกลิ้ง", "Khua kling curry paste", "1.5 tbsp"),
      ing("ใบมะกรูดซอย", "Sliced kaffir lime leaves", "1 tbsp"),
      ing("กระชายซอย", "Sliced fingerroot", "1 tbsp"),
    ],
    steps: [
      step("ผัดพริกแกงคั่วกลิ้งกับน้ำมันเล็กน้อยจนหอม", "Stir-fry the khua kling curry paste in a little oil until fragrant"),
      step("ใส่หมูสับ ผัดแห้งจนสุกทั่วโดยไม่ใส่น้ำ", "Add the ground pork, dry-fry until fully cooked without adding water"),
      step("ใส่กระชายซอย ผัดให้เข้ากัน", "Add sliced fingerroot, stir to combine"),
      step("โรยใบมะกรูดซอยก่อนเสิร์ฟ", "Top with sliced kaffir lime leaves before serving"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["lunch", "dinner"], regionTags: ["southern-thai"],
  },
  {
    slug: "gaeng-som-pla-kapong-tai",
    title_th: "แกงส้มปลากะพงใต้", title_en: "Southern Sour Fish Curry",
    calories: 200, protein: 34, carbs: 10, fat: 2,
    ingredients: [
      ing("ปลากะพงหั่นชิ้น", "Sea bass, sliced", "150g"),
      ing("พริกแกงส้ม", "Sour curry paste", "1 tbsp"),
      ing("มะขามเปียก", "Tamarind paste", "1 tbsp"),
      ing("มะละกอดิบหั่นชิ้น", "Green papaya, sliced", "1 cup"),
      ing("น้ำปลา", "Fish sauce", "1 tbsp"),
    ],
    steps: [
      step("ต้มน้ำให้เดือด ละลายพริกแกงส้มลงไป", "Bring water to a boil, dissolve the sour curry paste"),
      step("ใส่มะละกอ ต้มจนเริ่มนุ่ม", "Add papaya, simmer until starting to soften"),
      step("ใส่ปลา ต้มจนสุก", "Add the fish, simmer until cooked"),
      step("ปรุงรสด้วยมะขามเปียกและน้ำปลา เสิร์ฟร้อน", "Season with tamarind paste and fish sauce, serve hot"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["lunch", "dinner"], regionTags: ["southern-thai"],
  },
  {
    slug: "pad-sataw-goong",
    title_th: "ผัดสะตอกุ้ง", title_en: "Stink Bean Stir-Fry with Shrimp",
    calories: 190, protein: 33, carbs: 8, fat: 5,
    ingredients: [
      ing("กุ้ง", "Shrimp", "150g"),
      ing("สะตอ", "Stink beans", "1 cup"),
      ing("พริกแกงเผ็ด", "Red curry paste", "1 tbsp"),
      ing("ใบมะกรูดซอย", "Sliced kaffir lime leaves", "1 tbsp"),
    ],
    steps: [
      step("ผัดพริกแกงกับน้ำมันเล็กน้อยจนหอม", "Stir-fry the curry paste in a little oil until fragrant"),
      step("ใส่กุ้ง ผัดจนเริ่มเปลี่ยนสี", "Add shrimp, stir-fry until it starts to change color"),
      step("ใส่สะตอ ผัดจนกุ้งสุกทั่ว", "Add stink beans, stir-fry until the shrimp is fully cooked"),
      step("โรยใบมะกรูดซอย เสิร์ฟ", "Top with sliced kaffir lime leaves, serve"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["lunch", "dinner"], regionTags: ["southern-thai"],
  },
  {
    slug: "pla-pao-kleua",
    title_th: "ปลาเผาเกลือ", title_en: "Salt-Grilled Fish",
    calories: 230, protein: 48, carbs: 0, fat: 4,
    ingredients: [
      ing("ปลานิลทั้งตัว", "Whole tilapia", "1 fish, ~350g"),
      ing("เกลือหยาบ", "Coarse salt", "for crusting"),
      ing("ตะไคร้", "Lemongrass", "2 stalks"),
      ing("ใบมะกรูด", "Kaffir lime leaves", "3 leaves"),
    ],
    steps: [
      step("ล้างปลาให้สะอาด ยัดไส้ด้วยตะไคร้และใบมะกรูด", "Clean the fish well, stuff the cavity with lemongrass and kaffir lime leaves"),
      step("พอกตัวปลาด้วยเกลือหยาบให้ทั่ว", "Coat the fish thoroughly with coarse salt"),
      step("ย่างบนเตาถ่านจนเปลือกเกลือแข็งและปลาสุกทั่ว", "Grill over charcoal until the salt crust hardens and the fish is fully cooked"),
      step("เคาะเปลือกเกลือออก แกะเนื้อปลา เสิร์ฟพร้อมน้ำจิ้มซีฟู้ด", "Crack off the salt crust, flake the fish, serve with seafood dipping sauce"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "goong-pao",
    title_th: "กุ้งเผา", title_en: "Grilled Prawns",
    calories: 190, protein: 40, carbs: 4, fat: 2,
    ingredients: [
      ing("กุ้งแม่น้ำหรือกุ้งตัวใหญ่", "River prawns or large shrimp", "200g"),
      ing("น้ำจิ้มซีฟู้ด", "Seafood dipping sauce", "for serving"),
    ],
    steps: [
      step("ผ่ากุ้งตามยาวเล็กน้อยเพื่อให้สุกทั่วถึง", "Butterfly the prawns slightly for even cooking"),
      step("ตั้งเตาถ่านให้ร้อนปานกลาง", "Heat the charcoal grill to medium heat"),
      step("ย่างกุ้งจนเปลือกเปลี่ยนเป็นสีส้มแดงและเนื้อสุก", "Grill until the shell turns red-orange and the flesh is cooked through"),
      step("เสิร์ฟร้อนๆ พร้อมน้ำจิ้มซีฟู้ด", "Serve hot with seafood dipping sauce"),
    ],
    dietTags: ["high-protein", "low-cal"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "pla-kapong-neung-manao",
    title_th: "ปลากะพงนึ่งมะนาว", title_en: "Steamed Sea Bass with Lime",
    calories: 230, protein: 42, carbs: 6, fat: 3,
    ingredients: [
      ing("ปลากะพงทั้งตัว", "Whole sea bass", "1 fish, ~300g"),
      ing("น้ำมะนาว", "Lime juice", "3 tbsp"),
      ing("กระเทียม", "Garlic", "5 cloves, minced"),
      ing("พริกขี้หนู", "Thai chilies", "5, chopped"),
      ing("น้ำปลา", "Fish sauce", "2 tbsp"),
    ],
    steps: [
      step("นึ่งปลาในลังถึงจนสุกทั่ว ประมาณ 15 นาที", "Steam the fish in a steamer basket until fully cooked, about 15 minutes"),
      step("ผสมน้ำมะนาว กระเทียม พริกขี้หนู และน้ำปลาเป็นน้ำราด", "Mix lime juice, garlic, chilies, and fish sauce to make the sauce"),
      step("ราดน้ำซอสลงบนปลาที่นึ่งสุกแล้ว", "Pour the sauce over the steamed fish"),
      step("เสิร์ฟทันทีขณะร้อน", "Serve immediately while hot"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "hoi-lai-pad-prik-pao",
    title_th: "หอยลายผัดพริกเผา", title_en: "Clams with Chili Paste",
    calories: 190, protein: 25, carbs: 12, fat: 5,
    ingredients: [
      ing("หอยลาย", "Clams", "200g"),
      ing("พริกเผา", "Roasted chili paste", "1.5 tbsp"),
      ing("กระเทียม", "Garlic", "3 cloves"),
      ing("ใบโหระพา", "Thai basil leaves", "1/2 cup"),
      ing("พริกชี้ฟ้า", "Spur chili", "1, sliced"),
    ],
    steps: [
      step("ล้างหอยลายให้สะอาด", "Rinse the clams thoroughly"),
      step("ผัดกระเทียมกับน้ำมันเล็กน้อยจนหอม ใส่พริกเผาผัดให้เข้ากัน", "Stir-fry garlic in a little oil until fragrant, add chili paste and stir to combine"),
      step("ใส่หอยลาย ผัดจนเปลือกเปิดและสุกทั่ว", "Add the clams, stir-fry until the shells open and they're fully cooked"),
      step("ใส่ใบโหระพาและพริกชี้ฟ้า ผัดให้เข้ากัน เสิร์ฟ", "Add basil and chili, toss to combine, serve"),
    ],
    dietTags: ["high-protein", "low-cal"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "tom-yum-pla",
    title_th: "ต้มยำปลา", title_en: "Tom Yum Pla (Fish Tom Yum)",
    calories: 190, protein: 33, carbs: 6, fat: 3,
    ingredients: [
      ing("ปลากะพงหั่นชิ้น", "Sea bass, sliced", "150g"),
      ing("ตะไคร้", "Lemongrass", "2 stalks"),
      ing("ใบมะกรูด", "Kaffir lime leaves", "4 leaves"),
      ing("พริกขี้หนู", "Thai chilies", "5 chilies"),
      ing("น้ำพริกเผา", "Roasted chili paste", "1 tbsp"),
    ],
    steps: [
      step("ต้มน้ำซุปกับตะไคร้และใบมะกรูดจนหอม", "Boil stock with lemongrass and kaffir lime leaves until fragrant"),
      step("ใส่ปลาและพริกขี้หนู ต้มจนปลาสุก", "Add fish and chilies, simmer until the fish is cooked"),
      step("ปรุงรสด้วยน้ำพริกเผา น้ำปลา และน้ำมะนาว", "Season with roasted chili paste, fish sauce, and lime juice"),
      step("ตักเสิร์ฟร้อนๆ", "Serve hot"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "pad-pak-ruam-tao-hoo",
    title_th: "ผัดผักรวมเต้าหู้", title_en: "Mixed Vegetable Tofu Stir-Fry",
    calories: 195, protein: 15, carbs: 16, fat: 9,
    ingredients: [
      ing("เต้าหู้แข็ง", "Firm tofu", "150g, cubed"),
      ing("ผักรวม (แครอท, บรอกโคลี, ข้าวโพดอ่อน)", "Mixed vegetables (carrot, broccoli, baby corn)", "1.5 cups"),
      ing("กระเทียม", "Garlic", "3 cloves"),
      ing("ซีอิ๊วขาว", "Light soy sauce", "1 tbsp"),
      ing("ซอสหอยนางรม", "Oyster sauce", "1 tbsp"),
    ],
    steps: [
      step("ทอดเต้าหู้ในน้ำมันเล็กน้อยจนผิวเหลือง พักไว้", "Pan-fry the tofu in a little oil until golden, set aside"),
      step("ผัดกระเทียมกับน้ำมันเล็กน้อยจนหอม", "Stir-fry garlic in a little oil until fragrant"),
      step("ใส่ผักรวม ผัดจนเริ่มนุ่ม", "Add mixed vegetables, stir-fry until starting to soften"),
      step("ปรุงรสด้วยซีอิ๊วขาวและซอสหอยนางรม ใส่เต้าหู้กลับลงไป ผัดให้เข้ากัน เสิร์ฟ", "Season with light soy sauce and oyster sauce, return the tofu, toss to combine, serve"),
    ],
    dietTags: ["vegetarian", "low-cal"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "gaeng-liang",
    title_th: "แกงเลียง", title_en: "Gaeng Liang (Peppery Vegetable Soup)",
    calories: 140, protein: 6, carbs: 20, fat: 3,
    ingredients: [
      ing("ผักรวม (ฟักทอง, บวบ, ข้าวโพดอ่อน)", "Mixed vegetables (pumpkin, luffa, baby corn)", "2 cups"),
      ing("กะปิ", "Shrimp paste", "1 tsp"),
      ing("พริกไทยดำ", "Black peppercorns", "1 tsp"),
      ing("หอมแดง", "Shallot", "3 pieces"),
      ing("ใบแมงลัก", "Hairy basil leaves", "1/2 cup"),
    ],
    steps: [
      step("โขลกพริกไทย หอมแดง และกะปิให้ละเอียด", "Pound peppercorns, shallot, and shrimp paste until fine"),
      step("ต้มน้ำให้เดือด ละลายเครื่องที่โขลกลงไป", "Bring water to a boil, dissolve the pounded paste"),
      step("ใส่ผักรวม ต้มจนสุกนุ่ม", "Add mixed vegetables, simmer until tender"),
      step("ใส่ใบแมงลัก ปรุงรสด้วยน้ำปลา เสิร์ฟร้อน", "Add hairy basil, season with fish sauce, serve hot"),
    ],
    mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "yum-hed-ruam",
    title_th: "ยำเห็ดรวม", title_en: "Mixed Mushroom Salad",
    calories: 100, protein: 7, carbs: 16, fat: 1,
    ingredients: [
      ing("เห็ดรวม (เห็ดฟาง, เห็ดนางฟ้า, เห็ดหอม)", "Mixed mushrooms (straw, oyster, shiitake)", "200g"),
      ing("หอมแดง", "Shallot", "2 pieces, sliced"),
      ing("พริกขี้หนู", "Thai chilies", "3, sliced"),
      ing("น้ำมะนาว", "Lime juice", "2 tbsp"),
      ing("ผักชี", "Cilantro", "for garnish"),
    ],
    steps: [
      step("ลวกเห็ดรวมในน้ำเดือดจนสุก สะเด็ดน้ำ", "Blanch the mixed mushrooms in boiling water until cooked, drain"),
      step("ผสมน้ำปลา น้ำมะนาว และพริกขี้หนูเป็นน้ำยำ", "Mix fish sauce, lime juice, and chilies to make the dressing"),
      step("คลุกเห็ดกับหอมแดงและน้ำยำให้เข้ากัน", "Toss the mushrooms with shallot and dressing to combine"),
      step("โรยผักชี เสิร์ฟ", "Garnish with cilantro, serve"),
    ],
    dietTags: ["vegetarian", "low-cal"], mealTypeTags: ["lunch", "snack"], regionTags: ["central-thai"],
  },
  {
    slug: "pad-priao-wan-tao-hoo",
    title_th: "ผัดเปรี้ยวหวานเต้าหู้", title_en: "Sweet and Sour Tofu",
    calories: 205, protein: 14, carbs: 19, fat: 8,
    ingredients: [
      ing("เต้าหู้แข็ง", "Firm tofu", "150g, cubed"),
      ing("สับปะรด", "Pineapple", "1/2 cup, chunks"),
      ing("หอมใหญ่", "Onion", "1/2, chunks"),
      ing("พริกหยวก", "Bell pepper", "1/2, chunks"),
      ing("ซอสมะเขือเทศ", "Tomato sauce", "2 tbsp"),
      ing("น้ำส้มสายชู", "Vinegar", "1 tbsp"),
    ],
    steps: [
      step("ทอดเต้าหู้ในน้ำมันเล็กน้อยจนผิวเหลือง พักไว้", "Pan-fry the tofu in a little oil until golden, set aside"),
      step("ผัดหอมใหญ่และพริกหยวกจนเริ่มนุ่ม", "Stir-fry onion and bell pepper until starting to soften"),
      step("ใส่ซอสมะเขือเทศ น้ำส้มสายชู และสับปะรด ผัดให้เข้ากัน", "Add tomato sauce, vinegar, and pineapple, stir to combine"),
      step("ใส่เต้าหู้กลับลงไป ผัดให้เข้ากัน เสิร์ฟ", "Return the tofu, toss to combine, serve"),
    ],
    dietTags: ["vegetarian", "low-cal"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "tom-yum-hed",
    title_th: "ต้มยำเห็ด", title_en: "Mushroom Tom Yum",
    calories: 100, protein: 7, carbs: 14, fat: 2,
    ingredients: [
      ing("เห็ดรวม (เห็ดฟาง, เห็ดนางฟ้า)", "Mixed mushrooms (straw, oyster)", "200g"),
      ing("ตะไคร้", "Lemongrass", "2 stalks"),
      ing("ใบมะกรูด", "Kaffir lime leaves", "4 leaves"),
      ing("พริกขี้หนู", "Thai chilies", "4 chilies"),
      ing("น้ำมะนาว", "Lime juice", "2 tbsp"),
    ],
    steps: [
      step("ต้มน้ำซุปผักกับตะไคร้และใบมะกรูดจนหอม", "Boil vegetable stock with lemongrass and kaffir lime leaves until fragrant"),
      step("ใส่เห็ดรวมและพริกขี้หนู ต้มจนเห็ดสุก", "Add mixed mushrooms and chilies, simmer until the mushrooms are cooked"),
      step("ปรุงรสด้วยซีอิ๊วขาวและน้ำมะนาว", "Season with light soy sauce and lime juice"),
      step("ตักเสิร์ฟร้อนๆ", "Serve hot"),
    ],
    dietTags: ["vegetarian", "low-cal"], mealTypeTags: ["lunch", "dinner"], regionTags: ["central-thai"],
  },
  {
    slug: "salad-kaek",
    title_th: "สลัดแขก", title_en: "Thai Peanut Salad",
    calories: 220, protein: 6, carbs: 22, fat: 12,
    ingredients: [
      ing("ผักรวม (กะหล่ำปลี, แตงกวา, มะเขือเทศ)", "Mixed vegetables (cabbage, cucumber, tomato)", "2 cups"),
      ing("ไข่ต้ม", "Boiled egg", "1, sliced"),
      ing("มันฝรั่งต้ม", "Boiled potato", "1/2 cup, cubed"),
      ing("ถั่วลิสงป่น", "Ground peanuts", "2 tbsp"),
      ing("น้ำสลัดถั่วรสเผ็ด (ลดน้ำตาล)", "Spicy peanut dressing (reduced sugar)", "3 tbsp"),
    ],
    steps: [
      step("จัดผักรวม ไข่ต้ม และมันฝรั่งต้มลงในจาน", "Arrange the mixed vegetables, boiled egg, and potato on a plate"),
      step("ผสมน้ำสลัดถั่วให้เข้ากัน", "Mix the peanut dressing until combined"),
      step("ราดน้ำสลัดลงบนผัก", "Pour the dressing over the vegetables"),
      step("โรยถั่วลิสงป่น เสิร์ฟ", "Sprinkle with ground peanuts, serve"),
    ],
    dietTags: ["vegetarian"], mealTypeTags: ["lunch", "snack"], regionTags: ["central-thai"],
  },
  {
    slug: "jok-moo",
    title_th: "โจ๊กหมู", title_en: "Rice Porridge with Pork",
    calories: 350, protein: 26, carbs: 31, fat: 12,
    ingredients: [
      ing("ข้าวต้มสุก (โจ๊ก)", "Cooked rice porridge base", "200g"),
      ing("หมูสันในสับ", "Ground pork tenderloin", "100g"),
      ing("ไข่ไก่", "Egg", "1 large"),
      ing("ขิงซอย", "Ginger, julienned", "1 tbsp"),
      ing("ต้นหอมและผักชี", "Spring onion and cilantro", "for garnish"),
    ],
    steps: [
      step("ต้มโจ๊กให้ร้อนได้ที่", "Heat the rice porridge base until hot"),
      step("ปั้นหมูสับเป็นก้อนเล็กๆ ใส่ลงในโจ๊กที่กำลังเดือด", "Form the ground pork into small balls, drop into the simmering porridge"),
      step("ต้มจนหมูสุก ตอกไข่ลงไปคนให้สุก", "Simmer until the pork is cooked, crack in the egg and stir until cooked"),
      step("ปรุงรสด้วยซีอิ๊วขาว โรยขิง ต้นหอม และผักชี เสิร์ฟร้อน", "Season with light soy sauce, top with ginger, spring onion, and cilantro, serve hot"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["breakfast", "one-dish"], regionTags: ["central-thai"],
  },
  {
    slug: "khao-tom-pla",
    title_th: "ข้าวต้มปลา", title_en: "Fish Rice Soup",
    calories: 290, protein: 35, carbs: 30, fat: 3,
    ingredients: [
      ing("ข้าวสวย", "Steamed rice", "150g"),
      ing("ปลากะพงหั่นชิ้น", "Sea bass, sliced", "150g"),
      ing("ขิงซอย", "Ginger, julienned", "1 tbsp"),
      ing("ต้นหอมและผักชี", "Spring onion and cilantro", "for garnish"),
      ing("ซีอิ๊วขาว", "Light soy sauce", "1 tbsp"),
    ],
    steps: [
      step("ต้มน้ำซุปกับขิงให้เดือด", "Bring stock to a boil with ginger"),
      step("ใส่ข้าวสวย ต้มจนเดือดอีกครั้ง", "Add the steamed rice, bring back to a boil"),
      step("ใส่ปลา ต้มจนสุก", "Add the fish, simmer until cooked"),
      step("ปรุงรสด้วยซีอิ๊วขาว โรยต้นหอมและผักชี เสิร์ฟร้อน", "Season with light soy sauce, top with spring onion and cilantro, serve hot"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["breakfast", "one-dish"], regionTags: ["central-thai"],
  },
  {
    slug: "khai-look-koei",
    title_th: "ไข่ลูกเขย", title_en: "Son-in-Law Eggs (Reduced Sugar)",
    calories: 200, protein: 12, carbs: 15, fat: 10,
    ingredients: [
      ing("ไข่ไก่ต้ม", "Boiled eggs", "2 large"),
      ing("น้ำมะขามเปียก", "Tamarind paste", "2 tbsp"),
      ing("น้ำตาลปี๊บ (ลดปริมาณ)", "Palm sugar (reduced)", "1 tbsp"),
      ing("หอมแดงเจียว", "Fried shallot", "for garnish"),
      ing("พริกชี้ฟ้าซอย", "Sliced spur chili", "for garnish"),
    ],
    steps: [
      step("ทอดไข่ต้มในน้ำมันเล็กน้อยจนผิวเหลืองกรอบ", "Pan-fry the boiled eggs in a little oil until the surface is golden and slightly crisp"),
      step("เคี่ยวน้ำมะขามเปียกกับน้ำตาลปี๊บและน้ำปลาจนข้น", "Simmer tamarind paste with palm sugar and fish sauce until thickened"),
      step("ผ่าไข่ครึ่งซีก จัดใส่จาน", "Halve the eggs, arrange on a plate"),
      step("ราดน้ำมะขาม โรยหอมแดงเจียวและพริกชี้ฟ้า เสิร์ฟ", "Pour the tamarind sauce over, top with fried shallot and chili, serve"),
    ],
    mealTypeTags: ["breakfast", "snack"], regionTags: ["central-thai"],
  },
  {
    slug: "khai-toon",
    title_th: "ไข่ตุ๋น", title_en: "Thai Steamed Egg",
    calories: 220, protein: 25, carbs: 1, fat: 12,
    ingredients: [
      ing("ไข่ไก่", "Eggs", "2 large"),
      ing("หมูสันในสับ", "Ground pork tenderloin", "50g"),
      ing("น้ำซุป", "Stock", "150ml"),
      ing("ต้นหอม", "Spring onion", "1 stalk, chopped"),
      ing("ซีอิ๊วขาว", "Light soy sauce", "1 tsp"),
    ],
    steps: [
      step("ตีไข่กับน้ำซุปและซีอิ๊วขาวให้เข้ากัน กรองผ่านตะแกรง", "Whisk eggs with stock and light soy sauce, strain through a sieve"),
      step("ใส่หมูสับลงในถ้วยตุ๋น เทไข่ที่กรองแล้วลงไป", "Place the ground pork in a steaming bowl, pour in the strained egg mixture"),
      step("นึ่งด้วยไฟกลางประมาณ 12-15 นาทีจนไข่สุกและเนื้อเนียน", "Steam over medium heat for 12-15 minutes until set and smooth"),
      step("โรยต้นหอม เสิร์ฟร้อน", "Top with spring onion, serve hot"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["lunch", "dinner", "one-dish"], regionTags: ["central-thai"],
  },
  {
    slug: "kuay-teow-tom-yum",
    title_th: "ก๋วยเตี๋ยวต้มยำ", title_en: "Tom Yum Noodle Soup",
    calories: 370, protein: 27, carbs: 53, fat: 4,
    ingredients: [
      ing("เส้นเล็ก", "Thin rice noodles", "150g"),
      ing("กุ้งและหมูสันในสับ", "Shrimp and ground pork tenderloin", "100g total"),
      ing("ถั่วงอก", "Bean sprouts", "1/2 cup"),
      ing("น้ำพริกเผา", "Roasted chili paste", "1 tbsp"),
      ing("ตะไคร้และใบมะกรูด", "Lemongrass and kaffir lime leaves", "for the broth"),
    ],
    steps: [
      step("ต้มน้ำซุปกับตะไคร้และใบมะกรูดจนหอม", "Boil stock with lemongrass and kaffir lime leaves until fragrant"),
      step("ใส่กุ้งและหมูสับ ต้มจนสุก", "Add shrimp and ground pork, simmer until cooked"),
      step("ปรุงรสด้วยน้ำพริกเผา น้ำปลา และน้ำมะนาว", "Season with roasted chili paste, fish sauce, and lime juice"),
      step("ลวกเส้นเล็กและถั่วงอกให้สุก จัดใส่ชาม ราดน้ำซุป เสิร์ฟ", "Blanch the noodles and bean sprouts until cooked, place in a bowl, ladle over the broth, serve"),
    ],
    mealTypeTags: ["lunch", "dinner", "one-dish"], regionTags: ["central-thai"],
  },
  {
    slug: "bami-kiew-moo-daeng",
    title_th: "บะหมี่เกี๊ยวหมูแดง", title_en: "Red Pork Wonton Noodles",
    calories: 540, protein: 41, carbs: 71, fat: 9,
    ingredients: [
      ing("บะหมี่ไข่", "Egg noodles", "100g dry weight"),
      ing("หมูแดง (สันในย่างเคลือบซอสลดน้ำตาล)", "Red pork (roasted lean pork, reduced-sugar glaze)", "100g, sliced"),
      ing("เกี๊ยวหมูนึ่ง", "Steamed pork wontons", "4 pieces"),
      ing("ผักกาดเขียว", "Bok choy", "1/2 cup"),
      ing("ซีอิ๊วขาว", "Light soy sauce", "1 tbsp"),
    ],
    steps: [
      step("ลวกบะหมี่ไข่และผักกาดเขียวในน้ำเดือดจนสุก สะเด็ดน้ำ", "Blanch the egg noodles and bok choy in boiling water until cooked, drain"),
      step("จัดบะหมี่ใส่ชาม ปรุงรสด้วยซีอิ๊วขาว", "Place the noodles in a bowl, season with light soy sauce"),
      step("วางหมูแดงหั่นชิ้นและเกี๊ยวนึ่งลงด้านบน", "Top with sliced red pork and steamed wontons"),
      step("ราดน้ำซุปร้อนๆ เสิร์ฟ", "Ladle over hot broth, serve"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "dinner", "one-dish"], regionTags: ["central-thai"],
  },
  {
    slug: "rad-na-moo",
    title_th: "ราดหน้าหมู", title_en: "Rad Na Pork",
    calories: 430, protein: 32, carbs: 59, fat: 6,
    ingredients: [
      ing("เส้นใหญ่", "Fresh flat rice noodles", "150g"),
      ing("หมูสันในหั่นบาง", "Lean pork loin, thinly sliced", "100g"),
      ing("คะน้า", "Chinese kale", "1 cup, chopped"),
      ing("ซีอิ๊วขาว", "Light soy sauce", "1 tbsp"),
      ing("แป้งมันละลายน้ำ", "Tapioca starch slurry", "for thickening"),
    ],
    steps: [
      step("ผัดเส้นใหญ่กับซีอิ๊วดำเล็กน้อยให้เข้ากัน จัดใส่จาน", "Stir-fry the flat noodles with a little dark soy sauce, place on a plate"),
      step("ผัดกระเทียมกับน้ำมันเล็กน้อยจนหอม ใส่หมูผัดจนสุก", "Stir-fry garlic in a little oil until fragrant, add pork and cook through"),
      step("ใส่คะน้าและน้ำซุป ต้มพอเดือด ปรุงรสด้วยซีอิ๊วขาว", "Add kale and stock, bring to a light boil, season with light soy sauce"),
      step("ใส่แป้งมันละลายน้ำเพื่อให้ข้น ราดลงบนเส้น เสิร์ฟ", "Add the tapioca slurry to thicken, pour over the noodles, serve"),
    ],
    dietTags: ["high-protein"], mealTypeTags: ["lunch", "dinner", "one-dish"], regionTags: ["central-thai"],
  },
  {
    slug: "por-pia-sod",
    title_th: "ปอเปี๊ยะสด", title_en: "Fresh Spring Rolls",
    calories: 180, protein: 14, carbs: 24, fat: 4,
    ingredients: [
      ing("แผ่นปอเปี๊ยะญวน", "Rice paper wrappers", "4 sheets"),
      ing("กุ้งต้ม", "Boiled shrimp", "100g"),
      ing("วุ้นเส้นลวก", "Blanched glass noodles", "30g"),
      ing("ผักสด (ผักกาดหอม, แตงกวา, สะระแหน่)", "Fresh vegetables (lettuce, cucumber, mint)", "1 cup"),
      ing("น้ำจิ้มถั่วลดน้ำตาล", "Reduced-sugar peanut dip", "2 tbsp"),
    ],
    steps: [
      step("จุ่มแผ่นปอเปี๊ยะในน้ำอุ่นให้นุ่ม", "Dip the rice paper in warm water until soft"),
      step("วางผักสด วุ้นเส้น และกุ้งลงบนแผ่นปอเปี๊ยะ", "Lay fresh vegetables, glass noodles, and shrimp on the wrapper"),
      step("ม้วนให้แน่น", "Roll up tightly"),
      step("เสิร์ฟพร้อมน้ำจิ้มถั่ว", "Serve with the peanut dip"),
    ],
    dietTags: ["high-protein", "low-cal"], mealTypeTags: ["lunch", "snack"], regionTags: ["central-thai"],
  },
  {
    slug: "tod-man-pla",
    title_th: "ทอดมันปลา", title_en: "Thai Fish Cakes (Baked)",
    calories: 240, protein: 44, carbs: 4, fat: 5,
    ingredients: [
      ing("เนื้อปลากะพงบด", "Ground sea bass", "200g"),
      ing("พริกแกงแดง", "Red curry paste", "1.5 tbsp"),
      ing("ถั่วฝักยาวซอย", "Sliced long beans", "1/4 cup"),
      ing("ใบมะกรูดซอย", "Sliced kaffir lime leaves", "1 tbsp"),
      ing("ไข่ไก่", "Egg", "1, as binder"),
    ],
    steps: [
      step("ผสมเนื้อปลากับพริกแกงและไข่ นวดจนเหนียว", "Mix the fish with curry paste and egg, knead until sticky"),
      step("ใส่ถั่วฝักยาวและใบมะกรูดซอย คลุกให้เข้ากัน", "Add sliced long beans and kaffir lime leaves, mix to combine"),
      step("ปั้นเป็นแผ่นกลมแบน วางบนถาดอบ", "Shape into flat round patties, place on a baking tray"),
      step("อบที่ 200°C จนสุกทั่วและผิวเหลือง เสิร์ฟพร้อมน้ำจิ้ม", "Bake at 200°C until fully cooked and golden, serve with dipping sauce"),
    ],
    dietTags: ["high-protein", "low-carb"], mealTypeTags: ["snack", "lunch"], regionTags: ["southern-thai"],
  },
];

let written = 0;
for (const r of recipes) {
  const { slug, ...rest } = r;
  const data = { title_th: rest.title_th, title_en: rest.title_en, photo: `/images/${slug}.jpg`, ...rest };
  const frontmatter = stringify(data);
  writeFileSync(join(OUT_DIR, `${slug}.md`), `---\n${frontmatter}---\n`);
  written++;
}
console.log(`Wrote ${written} recipe files to ${OUT_DIR}`);
